import Head from 'next/head'
import localFont from 'next/font/local'

import SidebarProvider from '@/Providers/SidebarProvider';

//css
import styles from '@/styles/Home.module.css'
import MenuPage from './menu';

// open sans common font
const openSans = localFont({
  src: "../assets/fonts/OpenSans-Medium.ttf",
  variable: "--open-sans-mediu"
});

/**
 * [Home] - Home page
 * @returns Home
 */
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${openSans.variable}`}>
          hello
      </main>
    </>
  )
}
